# Generated by Django 3.2 on 2021-04-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
