# Generated by Django 3.2 on 2021-04-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_remove_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at_timestamp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline_timestamp',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
