# Generated by Django 3.2 on 2021-04-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_auto_20210428_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
