# Generated by Django 3.2 on 2021-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0016_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
