# Generated by Django 3.2 on 2021-05-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0018_auto_20210503_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
